### ISSUE TITLE
KeyError: 'n_0_3'

### ISSUE THREAD

**Issue by HappyDay-design** [3neutronstar/traffic-optimization_RL#3]
Hello
I have just downloaded your model and tried to run it.
But I got errors when running the command      "python ./Experiment/run.py simulate"

Traceback (most recent call last):
  File "./Experiment/run.py", line 263, in <module>
    main(sys.argv[1:])
  File "./Experiment/run.py", line 206, in main
    NET_CONFIGS = network.get_configs()
  File "/home/osboxes/Desktop/traffic-optimization_RL/Experiment/Network/grid.py", line 431, in get_configs
    traffic_info[tl_rl['id']]['phase_list'] = self._phase_list()
KeyError: 'n_0_3'

**Comment by 3neutronstar** [comment]
https://github.com/3neutronstar/traffic-optimization_RL/blob/3a7623e36b746d50eff37cc35b08999888a4d999/Experiment/Network/grid.py#L417

I think you need to add the key and value in this dictionary variable.
